"""learned_equipment_level table

Revision ID: 1215f787176d
Revises: d247740d0e37
Create Date: 2026-06-07 23:06:27.501107

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1215f787176d'
down_revision: str | None = 'd247740d0e37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_equipment_level',
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('base_equipment_level', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('item_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learned_equipment_level')
    # ### end Alembic commands ###
