"""initial 5 tables

Revision ID: d247740d0e37
Revises: 
Create Date: 2026-06-04 10:15:23.354153

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd247740d0e37'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('notice_alert', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sunday_alert', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id')
    )
    op.create_table('error_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('command', sa.String(length=64), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_ocid', sa.String(length=128), nullable=True),
    sa.Column('error_type', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_cache',
    sa.Column('ocid', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ocid', 'type', 'date')
    )
    op.create_table('notice_state',
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('last_identifier', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('registration',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('maple_nickname', sa.String(length=64), nullable=False),
    sa.Column('ocid', sa.String(length=128), nullable=False),
    sa.Column('api_key_encrypted', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'discord_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    op.drop_table('notice_state')
    op.drop_table('history_cache')
    op.drop_table('error_log')
    op.drop_table('channel_settings')
    # ### end Alembic commands ###
