"""exp_snapshot table + channel_settings.exp_alert

Revision ID: e7aed951afb2
Revises: 1215f787176d
Create Date: 2026-06-14 13:30:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7aed951afb2"
down_revision: str | None = "1215f787176d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exp_snapshot",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_user_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("character_level", sa.Integer(), nullable=False),
        sa.Column("total_exp", sa.BigInteger(), nullable=False),
        sa.Column("world_rank", sa.Integer(), nullable=True),
        sa.Column("exp_rate", sa.Float(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("guild_id", "discord_user_id", "snapshot_date"),
    )
    op.add_column(
        "channel_settings",
        sa.Column(
            "exp_alert",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channel_settings", "exp_alert")
    op.drop_table("exp_snapshot")
    # ### end Alembic commands ###
